name: AIS-catcher Control Panel
version: "0.1.0"
slug: ais_catcher_control
description: Remote AIS-catcher-control panel through Home Assistant ingress
url: https://github.com/nanamitm/AIS-catcher-HA/tree/main/ais_catcher_control
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_stream: true
panel_icon: mdi:tune-variant
panel_title: AIS Control
options:
  url: "http://192.168.1.10:8110"
  verify_ssl: true
schema:
  url: url
  verify_ssl: bool
