#!/usr/bin/env python3
"""Generate ais_catcher_edge/ from ais_catcher/.

The Edge add-on installs the rolling `Edge` build of AIS-catcher instead of a
tagged release, which is the only way to get managed mode until upstream tags
one. Everything else about it -- the Dockerfile, run.sh, nginx.conf, the
artwork -- is the stable add-on's, so it is generated rather than copied by
hand: two hand-maintained folders that are 95% identical drift, and the drift
is what breaks.

Every rule below asserts that it matched. Change the stable add-on in a way
that moves the text a rule is looking for and this script fails loudly with the
rule that needs updating, rather than quietly producing a stale Edge add-on.

    python tools/sync_edge.py            # write ais_catcher_edge/
    python tools/sync_edge.py --check    # fail if it is out of date (CI)
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, os.pardir)
SRC = os.path.join(ROOT, "ais_catcher")
DST = os.path.join(ROOT, "ais_catcher_edge")

YAML_HEADER = (
    "# Generated by tools/sync_edge.py from ais_catcher/. Do not edit by hand:\n"
    "# change the stable add-on and run the script.\n"
)
MD_HEADER = (
    "<!-- Generated by tools/sync_edge.py from ais_catcher/. Do not edit by\n"
    "     hand: change the stable add-on and run the script. -->\n\n"
)


class RuleError(Exception):
    pass


def sub(text, old, new, what):
    if old not in text:
        raise RuleError(f"{what}: the text this rule replaces is not there any more")
    return text.replace(old, new, 1)


def config_yaml(text):
    text = sub(text, "name: AIS-catcher Receiver\n",
               "name: AIS-catcher Receiver (Edge)\n", "config.yaml name")
    text = sub(text, "slug: ais_catcher\n", "slug: ais_catcher_edge\n",
               "config.yaml slug")

    version, count = re.subn(r'^version: "([^"]+)"$', r'version: "\1-edge"',
                             text, count=1, flags=re.M)
    if not count:
        raise RuleError("config.yaml version: no version line to suffix")
    text = version

    text = sub(
        text,
        "description: Run AIS-catcher itself on Home Assistant, with the SDR"
        " plugged into the host\n",
        "description: The Receiver add-on built against the rolling Edge build,"
        " for managed mode\n",
        "config.yaml description",
    )
    text = sub(text, "/tree/main/ais_catcher\n", "/tree/main/ais_catcher_edge\n",
               "config.yaml url")
    text = sub(text, "panel_title: AIS Receiver\n", "panel_title: AIS Edge\n",
               "config.yaml panel_title")

    # Managed mode brings up a web viewer of its own on the control port plus
    # one. Publishing it gives the rest of the network the same reach it has in
    # manual mode; the ingress panel uses it either way.
    text = sub(
        text,
        "ports:\n  8100/tcp: 8100\n  8118/tcp: 8118\n",
        "ports:\n  8100/tcp: 8100\n  8118/tcp: 8118\n  8119/tcp: 8119\n",
        "config.yaml ports",
    )
    text = sub(
        text,
        "    can also be selected for the sidebar; nothing listens here in manual mode.\n",
        "    can also be selected for the sidebar; nothing listens here in manual mode.\n"
        "  8119/tcp: >-\n"
        "    The web viewer managed mode brings up beside the dashboard. Nothing\n"
        "    listens here in manual mode, which uses 8100.\n",
        "config.yaml ports_description",
    )

    text = sub(text, "options:\n  mode: manual\n", "options:\n  mode: managed\n",
               "config.yaml default mode")
    return YAML_HEADER + text


def build_yaml(text):
    pinned, count = re.subn(r'^(\s*AIS_CATCHER_VERSION:) ".*"$', r'\1 "Edge"',
                            text, count=1, flags=re.M)
    if not count:
        raise RuleError("build.yaml: no AIS_CATCHER_VERSION line to repin")
    return YAML_HEADER + pinned


def docs_md(text):
    text = sub(text, "# AIS-catcher Receiver\n", "# AIS-catcher Receiver (Edge)\n",
               "DOCS.md title")
    text = sub(
        text,
        "Runs [AIS-catcher](https://github.com/jvde-github/AIS-catcher) on the Home\n",
        "**This is the [Receiver](../ais_catcher) add-on built against"
        " AIS-catcher's\nrolling `Edge` build, so that managed mode is"
        " available.** `Edge` is rebuilt\nfrom the upstream `main` branch and"
        " published to the same download URL, so\nevery rebuild of this add-on"
        " can install a different program, two people\ninstalling on different"
        " days do not get the same one, and an upstream mistake\nreaches you"
        " without anything changing here. Install the stable Receiver instead\n"
        "unless you specifically want managed mode; this add-on will be retired"
        " once a\ntagged AIS-catcher release contains it.\n\n"
        "Runs [AIS-catcher](https://github.com/jvde-github/AIS-catcher) on the Home\n",
        "DOCS.md banner",
    )
    text = sub(
        text,
        "**Managed mode needs a newer AIS-catcher than this add-on installs.** It is not\n"
        "in the v0.70 release; in that release `-E` means something else entirely. The\n"
        "add-on asks the binary what it supports and refuses to start with an\n"
        "explanation rather than passing on a confusing error, so if you select managed\n"
        "mode and the add-on stops with *\"This AIS-catcher does not have managed\n"
        "mode\"*, that is why. Raise `AIS_CATCHER_VERSION` in `build.yaml` and rebuild to\n"
        "use it.\n",
        "Managed mode is the default here, and works: it is what this add-on exists\n"
        "for. The add-on still asks the binary whether it supports managed mode before\n"
        "using it, so an Edge build that drops or renames it stops the add-on with an\n"
        "explanation rather than a confusing error from AIS-catcher.\n",
        "DOCS.md managed-mode availability",
    )
    text = sub(
        text,
        "| `mode` | `manual` | `manual` builds the command line",
        "| `mode` | `managed` | `manual` builds the command line",
        "DOCS.md mode default",
    )
    return MD_HEADER + text


def changelog_md(_text):
    return MD_HEADER + (
        "# Changelog\n"
        "\n"
        "This add-on is generated from [the Receiver add-on](../ais_catcher) and\n"
        "carries its changes; see [its changelog](../ais_catcher/CHANGELOG.md).\n"
        "\n"
        "What is different here is the AIS-catcher it installs: the rolling `Edge`\n"
        "build rather than a tagged release, which is what makes managed mode\n"
        "available. `Edge` moves without this add-on changing, so the version\n"
        "shown for the add-on says nothing about which AIS-catcher is inside it.\n"
        "The one it started with is the first line AIS-catcher logs.\n"
    )


def translations_yaml(text):
    return sub(
        text,
        "      Managed hands configuration to AIS-catcher's own dashboard, on port 8118\n"
        "      of this host, and ignores those options -- but needs a newer AIS-catcher\n"
        "      than this add-on installs.\n",
        "      Managed, the default here, hands configuration to AIS-catcher's own\n"
        "      dashboard on port 8118 of this host and ignores those options.\n",
        "translations mode description",
    )


TRANSFORMS = {
    "config.yaml": config_yaml,
    "build.yaml": build_yaml,
    "DOCS.md": docs_md,
    "CHANGELOG.md": changelog_md,
    os.path.join("translations", "en.yaml"): translations_yaml,
}


def generate():
    """The Edge add-on as {relative path: (bytes, mode)}."""
    out = {}
    for root, _dirs, files in os.walk(SRC):
        for name in sorted(files):
            path = os.path.join(root, name)
            rel = os.path.relpath(path, SRC)
            with open(path, "rb") as handle:
                blob = handle.read()
            transform = TRANSFORMS.get(rel)
            if transform is not None:
                blob = transform(blob.decode("utf-8")).encode("utf-8")
            out[rel] = (blob, os.stat(path).st_mode & 0o777)
    for rel in TRANSFORMS:
        if rel not in out:
            raise RuleError(f"{rel}: a rule exists for a file that is not there")
    return out


def write(generated):
    for rel, (blob, mode) in generated.items():
        path = os.path.join(DST, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as handle:
            handle.write(blob)
        os.chmod(path, mode)
    # A file dropped from the stable add-on has to disappear here too.
    for root, _dirs, files in os.walk(DST):
        for name in files:
            rel = os.path.relpath(os.path.join(root, name), DST)
            if rel not in generated:
                os.remove(os.path.join(root, name))
    return sorted(generated)


def check(generated):
    problems = []
    for rel, (blob, _mode) in sorted(generated.items()):
        path = os.path.join(DST, rel)
        if not os.path.exists(path):
            problems.append(f"missing: ais_catcher_edge/{rel}")
            continue
        with open(path, "rb") as handle:
            if handle.read() != blob:
                problems.append(f"stale:   ais_catcher_edge/{rel}")
    for root, _dirs, files in os.walk(DST):
        for name in files:
            rel = os.path.relpath(os.path.join(root, name), DST)
            if rel not in generated:
                problems.append(f"extra:   ais_catcher_edge/{rel}")
    return problems


if __name__ == "__main__":
    try:
        generated = generate()
    except RuleError as error:
        print(f"tools/sync_edge.py: {error}", file=sys.stderr)
        print("The stable add-on changed under a rule. Update the rule in this "
              "script so the Edge add-on keeps carrying the change.", file=sys.stderr)
        raise SystemExit(2)

    if "--check" in sys.argv:
        problems = check(generated)
        if problems:
            print("ais_catcher_edge/ is not what tools/sync_edge.py generates:")
            for problem in problems:
                print(" ", problem)
            print("\nRun: python tools/sync_edge.py")
            raise SystemExit(1)
        print("ais_catcher_edge/ is in sync")
    else:
        for rel in write(generated):
            print("wrote ais_catcher_edge/" + rel)
